services:
  frontend:
    build: ./frontend/test
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/test:/app
      - /app/node_modules
    networks:
      - app-network

  backend_db:
    build: ./backend_db
    ports:
      - "8000:8000"
    shm_size: '2gb'
    networks:
      - app-network

  copycat_api:
    build: ./copycat_api_tddd96
    ports:
      - "3100:3100"
    shm_size: '2gb'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge